% Project 2.1
% Author Jonas Melander

function [V] = CA_1D_ELE(v_0, n)
rule = zeros(8,1);
bin = de2bi(n);
rule((end-length(bin)+1):1:end) = bin(end:-1:1);
V = zeros(1,length(v_0));
for i = 2:length(v_0)-1
    V(i) = (v_0(i-1) && v_0(i) && v_0(i+1) && rule(1)) ...
        || (v_0(i-1) && v_0(i) && ~v_0(i+1) && rule(2)) ...
        || (v_0(i-1) && ~v_0(i) && v_0(i+1) && rule(3)) ...
        || (v_0(i-1) && ~v_0(i) && ~v_0(i+1) && rule(4)) ...
        || (~v_0(i-1) && v_0(i) && v_0(i+1) && rule(5)) ...
        || (~v_0(i-1) && v_0(i) && ~v_0(i+1) && rule(6)) ...
        || (~v_0(i-1) && ~v_0(i) && v_0(i+1) && rule(7)) ...
        || (~v_0(i-1) && ~v_0(i) && ~v_0(i+1) && rule(8));
end
    V(1) = (v_0(end) && v_0(1) && v_0(2) && rule(1)) ...
        || (v_0(end) && v_0(1) && ~v_0(2) && rule(2)) ...
        || (v_0(end) && ~v_0(1) && v_0(2) && rule(3)) ...
        || (v_0(end) && ~v_0(1) && ~v_0(2) && rule(4)) ...
        || (~v_0(end) && v_0(1) && v_0(2) && rule(5)) ...
        || (~v_0(end) && v_0(1) && ~v_0(2) && rule(6)) ...
        || (~v_0(end) && ~v_0(1) && v_0(2) && rule(7)) ...
        || (~v_0(end) && ~v_0(1) && ~v_0(2) && rule(8));

    V(end) = (v_0(end-1) && v_0(end) && v_0(1) && rule(1)) ...
        || (v_0(end-1) && v_0(end) && ~v_0(1) && rule(2)) ...
        || (v_0(end-1) && ~v_0(end) && v_0(1) && rule(3)) ...
        || (v_0(end-1) && ~v_0(end) && ~v_0(1) && rule(4)) ...
        || (~v_0(end-1) && v_0(end) && v_0(1) && rule(5)) ...
        || (~v_0(end-1) && v_0(end) && ~v_0(1) && rule(6)) ...
        || (~v_0(end-1) && ~v_0(end) && v_0(1) && rule(7)) ...
        || (~v_0(end-1) && ~v_0(end) && ~v_0(1) && rule(8));


end
